import { Geist, Geist_Mono, Playfair_Display, Poppins, Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";


// Geist Sans
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

// Geist Mono
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// Playfair Display
const playfairDisplay = Playfair_Display({
    variable: "--font-playfair",
    subsets: ["latin"],
});

// Poppins
const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"], // pick weights you need
});

// Lato
const lato = Lato({
    variable: "--font-lato",
    subsets: ["latin"],
    weight: ["300", "400", "700"], // pick weights you need
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body
            className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${playfairDisplay.variable}
          ${poppins.variable}
          ${lato.variable}
          antialiased
        `}
        >
        <Header />
        {children}
        <Footer />
        </body>
        </html>
    );
}